### ISSUE TITLE
Indicators do not provide configuration of undefined value

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc-technical-indicator#10]
The design guidelines state that:

> If a calculator creates 'undefined' values, the value used should be configurable.

exponential moving average, and potential others, violate this. 

It looks like sliding window is the only indicator that provides this functionality. Is it really necessary? The output of an indicator could easily be adapted after computation.

**Comment by ColinEberhardt** [comment]
Update:

 - [ ] Update the design documentation to specify undefined behaviour (i.e. same 'shape') as output
 - [ ] Check the above!
 - [ ] Move design docs into readme

**Comment by chrisprice** [comment]
@tlsim - are we good to close this now?

**Comment by tlsim** [comment]
Almost - just need to add the undefined input behaviour to the readme.
