### ISSUE TITLE
Indicators that have multiple input values should have consistent naming

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc-technical-indicator#11]
Elder Ray is inconsistent in that it has `highValue`, `lowValue` and `value` accessors. If an indicator depends on specific financial properties this should be reflected in all accessor names.

The design guidelines should be updated also - I think these guidelines should also be folder into the README - it shows a real thoroughness and a consistent API.

**Comment by tlsim** [comment]
Accessor names fixed in #12
Updating readme now part of #10
