### ISSUE TITLE
bug on example html page

### ISSUE THREAD

**Issue by chiu0602** [d3fc/d3fc-technical-indicator#47]
when displayed on browser, relativeStrengthIndex.html will shows with a horizontal line like "-----[object object]", and lots of error message `d3.js:7672 Error: <g> attribute transform: Trailing garbage, "translate(0, NaN)".` is shown on console.

**Comment by chrisprice** [comment]
Looks like the examples were missed when the `multi` `mapping` signature, updating them now.
