### ISSUE TITLE
Question: order of the input data?

### ISSUE THREAD

**Issue by whittlem** [d3fc/d3fc-technical-indicator#54]
I am trying out your package and have a question regarding the order of the input data array. Is the array ordered with latest prices first or last?

**Comment by ColinEberhardt** [comment]
It's latest date last, see the example data in the tests: https://github.com/d3fc/d3fc-technical-indicator/blob/master/test/data/input.csv

**Comment by whittlem** [comment]
Thanks, a lot. That's how I have it now but just wanted to make sure.
