### ISSUE TITLE
single-valued indicators should not have accessors

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc-technical-indicator#9]
moving average, exponential moving average, etc ... do not have accessors. However RSI does - for consistency, any indicator that only requires a single put value should not expose accessors.

The design guidelines should be updated accordingly.

(or, alternatively every indicator should expose accessors)

@chrisprice @tlsim - what do you think? I'm erring towards all indicators having accessors for a consistent API.

**Comment by chrisprice** [comment]
I think allowing an accessor to be specified is more in keeping with d3
(even v4) but agree we should be consistent whatever the choice.

Although now I'm thinking about it would a pre-map be so bad? Actually on
balance I think the consistency wins out...

**Comment by ColinEberhardt** [comment]
Talking gibberish, MA and EMA etc ... do have accessors, rebound from sliding window.
